### ISSUE TITLE
Contacting you

### ISSUE THREAD

**Issue by Adrianoross** [Mizogg/Mizogg-Tools#14]
Sent you a mail. Anticipating for your response.
Regards

**Comment by Mizogg** [comment]
Hi Adrianoross,
In reply to your email. 
I have read your post about your python program for Bitcoin. I am actually looking for a tool to acquire the public and private key of an address. Is there a possibility for that and can you render an assistance on how to acquire the tools. I will gladly appreciate your assistance.

I'm afraid it is only one way  we can go from Address to public or private. https://www.oreilly.com/library/view/mastering-bitcoin-2nd/9781491954379/ch04.html 
![image](https://user-images.githubusercontent.com/88630056/179359937-40814021-961b-44c9-b861-a2ca28b819de.png)

The public can be found but only with outgoing transactions.

Thanks Mizogg

**Comment by Mizogg** [comment]
""" I have made attempts to go through the instructions you gave but I do not understand what blockchain displayed when I opened the link you sent.
I only saw a public key displayed on blank page when I clicked on the link.
I can't understand how your program could help me find a public key of any address.
Hopefully you assist with some effective guidelines
Thank you
Best regards"""

Unless they have out going transactions then no public key. I link I provided shows you the public key for that address. That is because it has out going transaction.
